### ISSUE TITLE
怎么友盟没有起作用啊？

### ISSUE THREAD

**Issue by namelin2** [zxj963577494/cn.zxj.cordova.UmengAnalyticsPlugin#1]
按照上面的配置了，但是根本就不能生效，能不能多弄点注释，哪一步有什么作用标示出来，谢谢

**Comment by zxj963577494** [comment]
可以用的，请仔细再看下文档，具体作用请参考官方文档
[Android ](http://dev.umeng.com/analytics/android-doc/integration) || [Windows Phone 8 ](http://dev.umeng.com/analytics/wp-doc/wp8-integration) || [IOS ](http://dev.umeng.com/analytics/ios-doc/integration)

**Comment by zxj963577494** [comment]
@namelin2 
可以用的，请仔细再看下文档，具体作用请参考官方文档
[Android ](http://dev.umeng.com/analytics/android-doc/integration) || [Windows Phone 8 ](http://dev.umeng.com/analytics/wp-doc/wp8-integration) || [IOS ](http://dev.umeng.com/analytics/ios-doc/integration)
